### ISSUE TITLE
have some issues get help out the bot

### ISSUE THREAD

**Issue by werewolf26** [AlexFlipnote/discord_bot.py#27]
`
Traceback (most recent call last):
  File "C:\Users\ow that is the other\Desktop\discordbotpy\index.py", line 51, in <module>
    bot.run(config.token)
  File "C:\Users\ow that is the other\AppData\Roaming\Python\Python38\site-packages\discord\client.py", line 598, in run
    return future.result()
  File "C:\Users\ow that is the other\AppData\Roaming\Python\Python38\site-packages\discord\client.py", line 579, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\ow that is the other\AppData\Roaming\Python\Python38\site-packages\discord\client.py", line 543, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\ow that is the other\AppData\Roaming\Python\Python38\site-packages\discord\client.py", line 457, in connect
    await self._connect()
  File "C:\Users\ow that is the other\AppData\Roaming\Python\Python38\site-packages\discord\shard.py", line 274, in _connect
    f.result()
  File "C:\Users\ow that is the other\AppData\Roaming\Python\Python38\site-packages\discord\shard.py", line 78, in poll
    await self.ws.poll_event()
  File "C:\Users\ow that is the other\AppData\Roaming\Python\Python38\site-packages\discord\gateway.py", line 469, in poll_event
    await self.received_message(msg)
  File "C:\Users\ow that is the other\AppData\Roaming\Python\Python38\site-packages\discord\gateway.py", line 423, in received_message
    func(data)
  File "C:\Users\ow that is the other\AppData\Roaming\Python\Python38\site-packages\discord\state.py", line 409, in parse_message_reaction_add
    emoji = PartialEmoji.with_state(self, animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
KeyError: 'animated'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000020EDB233550>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python38\lib\asyncio\base_events.py", line 711, in call_soon
    self._check_closed()
  File "C:\Python38\lib\asyncio\base_events.py", line 504, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
C:\Users\ow that is the other\Desktop\discordbotpy\utils\http.py:24: RuntimeWarning: coroutine 'ClientSession.close' was never awaited`

When I type out help with the command reboot my bot when getting me these issues

**Comment by AlexFlipnote** [comment]
Update discord.py, that fixes the `KeyError: 'animated'` one.

**Comment by werewolf26** [comment]
oh okay

**Comment by werewolf26** [comment]
thank you it works

**Comment by sheeepdev** [comment]
I have this same problem and im on the latest version of discord.py

**Comment by Soheab** [comment]
> I have this same problem and im on the latest version of discord.py

You sure you are on the latest? There is no way  to get that error on 1.6. Try printing your version like so, `print(discord.__version__)` also i hope you install discord.py and not just discord.

**Comment by sheeepdev** [comment]
Im sure, I installed discord.py, version 1.6.0

**Comment by Soheab** [comment]
> Im sure, I installed discord.py, version 1.6.0

Send your error and printed version

**Comment by sheeepdev** [comment]
when i type the command u sent me I get error  Unable to initialize device PRN

**Comment by Soheab** [comment]
> when i type the command u sent me I get error Unable to initialize device PRN

What? You put that print under the `import discord` line in index and then run it

**Comment by sheeepdev** [comment]
It says 1.6.0.

**Comment by Soheab** [comment]
> It says 1.6.0.

Weird, and your error?

**Comment by sheeepdev** [comment]
Error when logging in: Improper token has been passed. (I actually put the correct token on the correct place.)
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000023EC27EB1F0>
Traceback (most recent call last):
  File "C:\Users\sheep\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\sheep\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\sheep\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\sheep\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
C:\Users\sheep\discord_bot.py\utils\http.py:24: RuntimeWarning: coroutine 'ClientSession.close' was never awaited

**Comment by Soheab** [comment]
Looks like your token is incorrect, see this https://media.discordapp.net/attachments/381963689470984203/514834919021740076/no_client_secret.jpg

**Comment by sheeepdev** [comment]
Error when logging in: Shard ID 0 is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

**Comment by Soheab** [comment]
> Error when logging in: Shard ID 0 is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

Did try the following: read it?

**Comment by sheeepdev** [comment]
> 
> 
> > Error when logging in: Shard ID 0 is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
> 
> Did try the following: read it?

how do I do it

**Comment by Igromik** [comment]
![image](https://user-images.githubusercontent.com/45947150/104756507-f4330180-576c-11eb-96dc-c07d921c0dcd.png)

**Comment by sheeepdev** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/45947150/104756507-f4330180-576c-11eb-96dc-c07d921c0dcd.png)

Thanks! Works now.
