### ISSUE TITLE
 from discord.utils import default not working

### ISSUE THREAD

**Issue by SashankPlayZ** [AlexFlipnote/discord_bot.py#31]
Whenever i try hosting my bot with a few code of this source code i get this error
well i rename utils to discord.utils thought it would work but didnt
if you could add me on discord and we discuss about it @Sashank#7581 or join my test server for a while https://discord.gg/s8S8a3d

**PS C:\Users\Sasha\Desktop\Toxy Bot> & C:/Users/Sasha/AppData/Local/Programs/Python/Python38-32/python.exe "c:/Users/Sasha/Desktop/Toxy Bot/Toxy.py"
cogs.Information can not be loaded:
Traceback (most recent call last):
  File "C:\Users\Sasha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 596, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module        
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed   
  File "c:\Users\Sasha\Desktop\Toxy Bot\cogs\Information.py", line 9, in <module>
    from discord.utils import default
ImportError: cannot import name 'default' from 'discord.utils' (C:\Users\Sasha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\utils.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:/Users/Sasha/Desktop/Toxy Bot/Toxy.py", line 83, in <module>
    raise e
  File "c:/Users/Sasha/Desktop/Toxy Bot/Toxy.py", line 80, in <module>
    client.load_extension(cog)
  File "C:\Users\Sasha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 653, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\Sasha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\bot.py", line 599, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.Information' raised an error: ImportError: cannot import name 'default' from 'discord.utils' (C:\Users\Sasha\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\utils.py)**

**Comment by Soheab** [comment]
Hey, `from utils import default` means its importing default.py from a **folder** called utils.

Copying code is always a bad move, complaining about makes it worse:)

**Comment by AlexFlipnote** [comment]
![image](https://user-images.githubusercontent.com/19587382/84890015-190dac00-b09a-11ea-8ac4-365153ab1af8.png)
