### ISSUE TITLE
The bot does not start

### ISSUE THREAD

**Issue by MEXXIO** [AlexFlipnote/discord_bot.py#36]
Hello, I'm trying to run the bot, I'm doing whatever it takes.  Bot starts but does not respond to commands.  There are no errors in the console. When I stop the CTRL + C script, I have something like this

```c:\Users\erwin\Desktop\discord_bot.py-master\utils\http.py:24: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
Task exception was never retrieved
future: <Task finished name='Task-9' coro=<AutoShardedConnectionState._delay_ready() done, defined at C:\Users\erwin\anaconda3\lib\site-packages\discord\state.py:1079> exception=AttributeError("'AutoShardedConnectionState' object has no attribute 'shard_id'")>
Traceback (most recent call last):
  File "C:\Users\erwin\anaconda3\lib\site-packages\discord\state.py", line 1118, in _delay_ready
    await utils.sane_wait_for(futures, timeout=timeout)
  File "C:\Users\erwin\anaconda3\lib\site-packages\discord\utils.py", line 352, in sane_wait_for
    raise asyncio.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\erwin\anaconda3\lib\site-packages\discord\state.py", line 1120, in _delay_ready
    log.warning('Shard ID %s failed to wait for chunks (timeout=%.2f) for %d guilds', self.shard_id,
AttributeError: 'AutoShardedConnectionState' object has no attribute 'shard_id'```

**Comment by AlexFlipnote** [comment]
Update discord.py

**Comment by MEXXIO** [comment]
I have discord.py 1.5.0a

**Comment by MEXXIO** [comment]
> Update discord.py

I have discord.py 1.5.0a

**Comment by AlexFlipnote** [comment]
Yeah I noticed that there's a bug with discord.AutoShardedBot, made a temporarily fix for it, looking into it.

**Comment by AlexFlipnote** [comment]
Fixed issue, reverted requirements.txt to stable release instead.
